Repository tommyxchow/frosty, pull requests merged in 2023-11, with the labels that each got.

#287 Migrate 7TV emotes to V3 API
  lib/apis/seventv_api.dart
  lib/main.dart
  lib/models/emotes.dart
  lib/models/emotes.g.dart
  test/emote_test.dart
Labels: bug fix

#291 Fix 7TV emotes not using custom names
  lib/apis/seventv_api.dart
  lib/models/emotes.dart
  lib/models/emotes.g.dart
  lib/models/irc.dart
Labels: bug fix

#292 Fix 7TV zero-width emotes not working
  lib/models/emotes.dart
  lib/models/emotes.g.dart
Labels: bug fix

#297 Upgrade to Flutter 3.16
  ios/Podfile.lock
  lib/screens/channel/chat/chat.dart
  lib/screens/channel/chat/widgets/chat_user_modal.dart
  lib/screens/channel/chat/widgets/reply_thread.dart
  lib/screens/settings/chat_settings.dart
  lib/theme.dart
  pubspec.lock
Labels: improvement

#298 Fix multiline message clipping text fields
  lib/screens/channel/chat/widgets/chat_bottom_bar.dart
  lib/theme.dart
Labels: bug fix

#300 Support replying to messages
  lib/screens/channel/chat/stores/chat_store.dart
  lib/screens/channel/chat/stores/chat_store.g.dart
  lib/screens/channel/chat/widgets/chat_bottom_bar.dart
  lib/screens/channel/chat/widgets/chat_message.dart
Labels: new feature

#301 Fix recent emotes not clearing
  lib/screens/channel/chat/details/chat_details.dart
  lib/screens/channel/chat/emote_menu/recent_emotes_panel.dart
Labels: bug fix

#302 Add quality change feature to custom overlay
  lib/screens/channel/video/video_overlay.dart
  lib/screens/channel/video/video_store.dart
  lib/screens/channel/video/video_store.g.dart
Labels: new feature

#305 Add support for 7TV emote update events
  lib/apis/seventv_api.dart
  lib/models/emotes.dart
  lib/models/emotes.g.dart
  lib/models/events.dart
  lib/models/events.g.dart
  lib/models/irc.dart
  lib/screens/channel/channel.dart
  lib/screens/channel/chat/stores/chat_assets_store.dart
  lib/screens/channel/chat/stores/chat_assets_store.g.dart
  lib/screens/channel/chat/stores/chat_store.dart
  lib/screens/channel/chat/stores/chat_store.g.dart
  lib/screens/channel/chat/widgets/chat_user_modal.dart
  lib/screens/channel/chat/widgets/reply_thread.dart
  lib/screens/channel/video/video_bar.dart
  lib/screens/home/search/search_results_channels.dart
  lib/screens/home/stream_list/large_stream_card.dart
  lib/screens/home/stream_list/stream_card.dart
  lib/screens/settings/account/blocked_users.dart
  lib/utils.dart
Labels: new feature

#307 Improve chat alerts and highlights design
  lib/screens/channel/chat/widgets/chat_message.dart
Labels: improvement

#309 Fix own display name not showing in chat
  lib/models/irc.dart
Labels: bug fix
