Repository tommyxchow/frosty, pull requests merged in 2024-08, with the labels that each got.

#364 Add option to sync message delay with stream latency
  lib/models/badges.g.dart
  lib/models/chatters.g.dart
  lib/models/emotes.g.dart
  lib/models/events.g.dart
  lib/models/stream.g.dart
  lib/screens/channel/chat/stores/chat_store.dart
  lib/screens/channel/chat/widgets/chat_bottom_bar.dart
  lib/screens/channel/video/video_store.dart
  lib/screens/settings/chat_settings.dart
  lib/screens/settings/stores/settings_store.dart
  lib/screens/settings/stores/settings_store.g.dart
Labels: new feature

#366 Upgrade Flutter and packages
  .gitignore
  analysis_options.yaml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
  ios/Podfile.lock
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
  pubspec.lock
  pubspec.yaml
Labels: improvement

#369 Upgrade to Flutter 3.24
  android/.gitignore
  android/app/build.gradle
  android/gradle.properties
  android/settings.gradle
  ios/Runner/AppDelegate.swift
  lib/screens/channel/chat/chat.dart
  lib/screens/channel/chat/widgets/chat_message.dart
  lib/widgets/block_report_modal.dart
  pubspec.lock
  pubspec.yaml
Labels: improvement

#370 Fix animated FFZ emotes not animating
  lib/models/emotes.dart
  lib/models/emotes.g.dart
Labels: bug fix

#371 Add options to disable emotes and badges
  lib/screens/channel/chat/chat.dart
  lib/screens/channel/chat/stores/chat_assets_store.dart
  lib/screens/channel/chat/stores/chat_assets_store.g.dart
  lib/screens/channel/chat/stores/chat_store.dart
  lib/screens/channel/chat/widgets/chat_bottom_bar.dart
  lib/screens/settings/chat_settings.dart
  lib/screens/settings/stores/settings_store.dart
  lib/screens/settings/stores/settings_store.g.dart
Labels: new feature

#372 Add photo view for thumbnails, emotes, and badges
  lib/models/irc.dart
  lib/screens/home/stream_list/stream_card.dart
  lib/widgets/photo_view.dart
  pubspec.lock
  pubspec.yaml
Labels: new feature

#373 Fix chat not disconnecting
  lib/screens/channel/chat/stores/chat_store.dart
Labels: bug fix

#374 Add option to enable historical recent messages in chat
  lib/apis/twitch_api.dart
  lib/models/irc.dart
  lib/screens/channel/channel.dart
  lib/screens/channel/chat/stores/chat_store.dart
  lib/screens/channel/chat/stores/chat_store.g.dart
  lib/screens/channel/chat/widgets/chat_message.dart
  lib/screens/onboarding/onboarding_setup.dart
  lib/screens/settings/chat_settings.dart
  lib/screens/settings/stores/settings_store.dart
  lib/screens/settings/stores/settings_store.g.dart
Labels: new feature

#375 Add release notes on launch
  assets/release-notes.md
  lib/screens/home/home.dart
  lib/screens/settings/other_settings.dart
  lib/screens/settings/widgets/release_notes.dart
  pubspec.lock
  pubspec.yaml
Labels: new feature

#378 Show video quality settings on iPad
  lib/main.dart
  lib/screens/channel/video/video_overlay.dart
  lib/screens/channel/video/video_store.dart
  lib/screens/channel/video/video_store.g.dart
  lib/screens/settings/video_settings.dart
  lib/utils.dart
Labels: ios, new feature

#379 Move exact matches of searched categories to the top
  lib/screens/home/search/search_store.dart
Labels: improvement

#381 Fix and add workaround for cookie banner blocking login
  lib/screens/onboarding/onboarding_login.dart
  lib/screens/settings/stores/auth_store.dart
Labels: bug fix
